### PR TITLE
fix: fix broken svg link for `gblog_arrow_right`,`PREV` and `NEXT` icon.

### PR DESCRIPTION
**Pull request by brickzzhang**
fix broken icon ref link.

### CODE REVIEW

**Comment by xoxys** [comment]
Why do you think it's broken? Some parts are using the GeekBlog IconFont instead of SVG sprites. This is intended and working.

image

**Comment by brickzzhang** [comment]
> Why do you think it's broken? Some parts are using the GeekBlog IconFont instead of SVG sprites. This is intended and working.
> 
> image

image

it's broken in my local, when i start hugo server, recieved a `WARN` message shown as below:

```bash
hugo server --watch=true
WARN 2022/11/14 16:31:09 Module "hugo-geekblog" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Start building sites …
```

is it related to this issue ?

**Comment by xoxys** [comment]
Might be unrelated, but please try the latest hugo release first. At least, I can't reproduce the issue yet.

**Comment by brickzzhang** [comment]
i upgrade hugo from:

```bash
❯ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended darwin/amd64 BuildDate: 2020-12-31T13:44:15Z
```

to

```bash
❯ hugo version
hugo v0.105.0+extended darwin/amd64 BuildDate=unknown
```

and still have this issue. I'm trying to troubleshoot it.

**Comment by xoxys** [comment]
What browser do you use? Please check the browser console for issues as well.

**Comment by brickzzhang** [comment]
> What browser do you use? Please check the browser console for issues as well.

i checked it on safari and works fine. Then cleaned cache on chrome and works fine now. I upgraded geekblog theme these days and encountered this issue. Guess it might be related to the font cache. Thanks a lot and will close this pr.

**Pull request closed without merging**
